### ISSUE TITLE
Description should be configurable for Report Portal for the consumers of teswiz

### ISSUE THREAD

**Issue by grover-ankit11** [znsio/teswiz#274]
Currently, the description for ReportPortal is being set in `Setup.java` like this:
```
System.setProperty("rp.description", configs.get(
                APP_NAME) + " End-2-End scenarios on " + currentPlatform.name());
```

If the consumer, want to change this to something else or don't want "End-2-End scenarios" as they may be dealing with component, contract test, there's no way which currently exist. We need to make "rp.description" configurable so that consumers can set this property on their own. If they're not setting, then the same value defined above should be used.

**Comment by anandbagmar** [comment]
you can try with this teswiz id: fb7da47c28

@grover-ankit11 
You can now provide the custom description in config.properties:

`RP_DESCRIPTION=custom description`

See changes done here: 
https://github.com/znsio/teswiz/commit/fb7da47c288592e2fefb76a507a96e7832bcceb7

**Comment by anandbagmar** [comment]
fixed in https://github.com/znsio/teswiz/commit/fb7da47c288592e2fefb76a507a96e7832bcceb7
